# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: types-pytz
  version: "2026.5.0.20261006"

package:
  name: ${{ name | lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/types_pytz-${{ version }}.tar.gz
  sha256: 1a522c2ec03aad8d4baaf97105958019ad51704b1e471c882d1c6ccea3e5e64b

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - package_contents:
      site_packages:
        - pytz-stubs/__init__.pyi
  - python:
      imports: []
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/python/typeshed
  summary: Typing stubs for pytz
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
